FROM centos:7
MAINTAINER Ansible Playbook Bundle Community
LABEL "com.redhat.apb.runtime"="2"

ENV USER_NAME=apb \
    USER_UID=1001 \
    BASE_DIR=/opt/apb
ENV HOME=${BASE_DIR}

RUN curl https://copr.fedorainfracloud.org/coprs/g/ansible-service-broker/ansible-service-broker-1.2.0-openshift-3.10/repo/epel-7/group_ansible-service-broker-ansible-service-broker-1.2.0-openshift-3.10-epel-7.repo -o /etc/yum.repos.d/asb.repo
RUN rpm --import https://copr-be.cloud.fedoraproject.org/results/@ansible-service-broker/ansible-service-broker-latest/pubkey.gpg \
 && yum -y install https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.5.9-1.el7.ans.noarch.rpm \
 && yum -y install epel-release centos-release-openshift-origin git \
    && yum -y install --setopt=tsflags=nodocs origin-clients python-openshift ansible-kubernetes-modules ansible-asb-modules apb-base-scripts python2-jmespath \
    && yum clean all

RUN mkdir -p /usr/share/ansible/openshift \
             /etc/ansible /opt/apb /opt/ansible \
             ${BASE_DIR}/{etc,.kube,.ansible/tmp} \
             && useradd -u ${USER_UID} -r -g 0 -M -d ${BASE_DIR} -b ${BASE_DIR} -s /sbin/nologin -c "apb user" ${USER_NAME} \
             && chown -R ${USER_NAME}:0 /opt/{ansible,apb} \
             && chmod -R g=u /opt/{ansible,apb} /etc/passwd

WORKDIR /opt/apb
ENTRYPOINT ["entrypoint.sh"]
